[versions]
# Project Versions
compileSdk = "36"
minSdk = "24"
targetSdk = "36"
applicationId = "com.ahmetsirim.unicocaseaivoicechatapp"
versionCode = "1"
versionName = "1.0"

# Android Gradle Plugin & Kotlin
androidGradlePlugin = "8.12.1"
kotlin = "2.2.10"

# AndroidX Core
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"

# Compose Dependencies
composeBom = "2025.08.00"

# Kotlinx Serialization
kotlinxSerializationJson = "1.9.0"

# Kotlinx Coroutines
kotlinxCoroutines = "1.10.2"

# Kotlin Symbol Processor (KSP)
ksp = "2.2.10-2.0.2"

# Retrofit & Moshi & OkHttp
retrofit = "3.0.0"
moshi = "1.15.2"
okhttpBom = "5.1.0"

# DataStore Preferences
datastorePreferences = "1.1.7"

# Room Database
roomCompiler = "2.7.2"
roomKtx = "2.7.2"

# Hilt & Javax
hilt = "2.57"
hiltNavigation = "1.2.0"
javaxInject = "1"

# Navigation Component
navigationComponent = "2.9.3"

# Firebase
firebaseBom = "34.1.0"
gmsGoogleServices = "4.4.3"
crashlytics = "3.0.6"
appdistribution = "5.1.1"

[libraries]
# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Compose Dependencies
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }

# Kotlinx Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

# Kotlinx Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Hilt & Javax
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }

# Navigation Component
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationComponent" }
navigation-common = { group = "androidx.navigation", name = "navigation-common", version.ref = "navigationComponent" }

# Retrofit & Moshi Converter
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi-converter = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }

# Moshi
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }

# OkHttp
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor" }

# DataStore Preferences
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }

# Room Database
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }

# Firebase Bill of Material (BoM) & Other Firebase Libraries
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "roomKtx" }
google-services = { id = "com.google.gms.google-services", version.ref = "gmsGoogleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "appdistribution" }